import os
from datetime import datetime


def save_html_report(target, ip, open_ports):

    os.makedirs("reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    filename = f"reports/scan_{timestamp}.html"

    html = f"""
<!DOCTYPE html>
<html>

<head>

<title>NetRecon Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    margin: 40px;
}}

.container {{
    background: white;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0px 0px 10px rgba(0,0,0,0.2);
}}

h1 {{
    color: #0d6efd;
}}

table {{
    width:100%;
    border-collapse: collapse;
    margin-top:20px;
}}

th {{
    background:#0d6efd;
    color:white;
    padding:12px;
}}

td {{
    border:1px solid #ddd;
    padding:10px;
    text-align:center;
}}

tr:nth-child(even){{
    background:#f2f2f2;
}}

.footer{{
    margin-top:25px;
    color:gray;
}}

</style>

</head>

<body>

<div class="container">

<h1>NetRecon Scan Report</h1>

<p><b>Target:</b> {target}</p>

<p><b>Resolved IP:</b> {ip}</p>

<p><b>Generated:</b> {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}</p>

<p><b>Total Open Ports:</b> {len(open_ports)}</p>

<table>

<tr>

<th>Port</th>
<th>Service</th>
<th>Banner</th>

</tr>
"""

    for port in open_ports:

        html += f"""

<tr>

<td>{port["port"]}</td>

<td>{port["service"]}</td>

<td>{port["banner"]}</td>

</tr>

"""

    html += """

</table>

<div class="footer">

Generated by <b>NetRecon</b>

</div>

</div>

</body>

</html>

"""

    with open(filename, "w", encoding="utf-8") as file:
        file.write(html)

    print("\n🌐 HTML Report Saved Successfully!")
    print(f"Location : {filename}")